### ISSUE TITLE
The "getting started" document is missing

### ISSUE THREAD

**Issue by shankari** [mapillary/map_matching#3]
It is unclear how a user goes about loading the data into PostGIS and invoking the matching...

**Comment by davidlowjw** [comment]
Hi @ptpt, is there a documentation somewhere? :)

**Comment by ptpt** [comment]
Hi @davidlowjw @shankari 

You need to have data imported before you use it. Take a look at the data import page: https://github.com/mapillary/map_matching/wiki/Data-Import and when you get the data imported, simply `python setup.py install` to install the library. And then you can find some examples here https://github.com/mapillary/map_matching/tree/master/examples

The MM algorithm provided by the library is simply a interface to use. Preparing data needed by the algorihm, however, need you to do a lot of work. That's why the example looks scary for the moment (I'm sorry for that). If it works for you I'll think about extract some common utils and put into the library to make it really "work nicely with PostGIS and OSM".

Any problem let me know.

**Comment by sammy-SC** [comment]
Hello @ptpt,

any progress on this?

**Comment by ptpt** [comment]
Hi all, we have switched to using https://github.com/valhalla/valhalla for performance reason. This repo is therefore inactive. Please take a look at Valhalla. It's easier to get started and much faster.
